name: calorie_ai_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  hugeicons: ^0.0.11
  flutter_svg: ^2.0.17
  flutter_local_notifications: ^17.2.2
  supabase_flutter: ^2.10.0
  health: ^13.1.4
  permission_handler: ^12.0.1
  camera: ^0.11.2
  image_picker: ^1.2.0
  http: ^1.5.0
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  in_app_review: ^2.0.10
  onesignal_flutter: ^5.3.4
  flutter_gen: ^5.11.0
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  purchases_flutter: ^9.9.0
  jwt_decoder: ^2.0.1
  share_plus: ^10.1.3
  flutter_timezone: ^5.0.1
  appsflyer_sdk: ^6.17.5
  device_info_plus: ^11.5.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
